/* Generated By:JavaCC: Do not edit this line. MojicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MojicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 2;
  /** RegularExpression Id. */
  int MAIN = 3;
  /** RegularExpression Id. */
  int LBRACE = 4;
  /** RegularExpression Id. */
  int RBRACE = 5;
  /** RegularExpression Id. */
  int LCURLY = 6;
  /** RegularExpression Id. */
  int RCURLY = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int OP_ATRB = 10;
  /** RegularExpression Id. */
  int PEV = 11;
  /** RegularExpression Id. */
  int V = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int RETURN = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int LEQ = 22;
  /** RegularExpression Id. */
  int TOKEN_skip = 23;
  /** RegularExpression Id. */
  int TOKEN_id = 24;
  /** RegularExpression Id. */
  int TOKEN_numliteral = 25;
  /** RegularExpression Id. */
  int OPA = 26;
  /** RegularExpression Id. */
  int OPM = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"void\"",
    "\"main\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"int\"",
    "\"bool\"",
    "\":=\"",
    "\";\"",
    "\",\"",
    "\"if\"",
    "\"do\"",
    "\"while\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"leq\"",
    "\"skip\"",
    "<TOKEN_id>",
    "<TOKEN_numliteral>",
    "<OPA>",
    "<OPM>",
  };

}
